"""MarkdownRenderer: a plain-text, portable, diffable report format.

Formats the shared ReportDocument directly as markdown (the "- " bullet
convention of its bodies already reads as markdown). Intentionally simple: for
debugging and version-control diffing, not the primary auditor-facing
deliverable (HTMLRenderer/PDFRenderer).
"""

from __future__ import annotations

from nssa.oae.reporting.context import OAEReport
from nssa.oae.reporting.models import EnrichmentResult
from nssa.oae.reporting.report import FindingSection, ReportDocument, ReportStats, build_report_document

_SEVERITY_LABELS = {"critical": "Critical", "high": "High", "medium": "Medium", "low": "Low", "other": "Other"}


class MarkdownRenderer:
    """Implements Renderer (content_type "text/markdown"); deterministic for the same input."""

    @property
    def content_type(self) -> str:
        return "text/markdown"

    def render(
        self, report: OAEReport, result: EnrichmentResult | None, *, policy_reference: str | None = None,
    ) -> bytes:
        document = build_report_document(report, result, policy_reference=policy_reference)
        blocks = [
            "# Network Segmentation Security Assessment Report",
            self._render_executive_summary(document),
            self._render_stats(document.stats),
            self._render_findings(document.findings),
            self._render_metadata(document),
        ]
        text = "\n\n".join(blocks)
        return (text + "\n").encode("utf-8")

    @staticmethod
    def _render_executive_summary(document: ReportDocument) -> str:
        return f"## Executive Summary\n\n{document.executive_summary}"

    @staticmethod
    def _render_stats(stats: ReportStats) -> str:
        severity_line = " | ".join(
            f"{_SEVERITY_LABELS.get(level, level.title())}: {count}" for level, count in stats.by_severity
        )
        lines = [f"**Total findings:** {stats.total}", severity_line]
        if stats.by_category:
            category_line = " | ".join(f"{name}: {count}" for name, count in stats.by_category)
            lines.append(category_line)
        return "\n\n".join(lines)

    def _render_findings(self, findings: tuple[FindingSection, ...]) -> str:
        if not findings:
            return "## Findings\n\nNo findings were identified during this audit."
        blocks = [self._render_finding(finding) for finding in findings]
        return "## Findings\n\n" + "\n\n".join(blocks)

    @staticmethod
    def _render_finding(finding: FindingSection) -> str:
        # Labels match the "####" section headers below and the HTML/PDF labels.
        meta_parts = [f"**Impacted Asset:** `{finding.impacted_asset}`"]
        if finding.violated_rule_ids:
            meta_parts.append("**Violated Policy Rules:** " + ", ".join(f"`{r}`" for r in finding.violated_rule_ids))
        if finding.compliance_control_ids:
            meta_parts.append("**Affected Compliance Controls:** " + ", ".join(f"`{c}`" for c in finding.compliance_control_ids))

        parts = [
            f"### {finding.finding_id} ({finding.severity}) -- {finding.title}",
            " &nbsp;|&nbsp; ".join(meta_parts),
            finding.summary,
            f"#### Technical Evidence\n\n{finding.technical_evidence}",
        ]
        if finding.policy_context:
            parts.append(f"#### Violated Policy Rules\n\n{finding.policy_context}")
        parts.append(f"#### Business Impact\n\n{finding.business_impact}")
        parts.append(f"#### Affected Compliance Controls\n\n{finding.compliance_mappings}")
        parts.append(f"#### Recommended Mitigations\n\n{finding.recommended_mitigations}")
        return "\n\n".join(parts)

    @staticmethod
    def _render_metadata(document: ReportDocument) -> str:
        metadata = document.metadata
        provenance = (
            "All findings and technical evidence in this report were generated by NSSA from "
            "observed network behaviour."
        )
        policy_line = f"- Policy reference: {metadata.policy_reference}\n" if metadata.policy_reference else ""
        if not metadata.performed:
            return (
                "## Report Metadata\n\n_Supplementary information._\n\n"
                f"{provenance} AI enrichment was not performed for this report -- no LLM-added "
                f"content (summaries, business impact, compliance mappings, mitigations) is present.\n\n"
                f"{policy_line}"
            ).rstrip()

        lines = [
            f"- Provider: {metadata.provider}",
            f"- Model: {metadata.model}",
            f"- Prompt version: {metadata.prompt_version}",
        ]
        if metadata.generated_at:
            lines.append(f"- Generated at: {metadata.generated_at}")
        if metadata.latency_ms is not None:
            lines.append(f"- Latency: {metadata.latency_ms:.0f} ms")
        if metadata.input_tokens is not None or metadata.output_tokens is not None:
            lines.append(f"- Tokens: {metadata.input_tokens or 0} in / {metadata.output_tokens or 0} out")

        return (
            "## Report Metadata\n\n_Supplementary information._\n\n"
            f"{provenance} Only the executive summary, each finding's summary, business impact "
            "assessment, compliance mappings, and mitigation suggestions were added by the model "
            f"below.\n\n{policy_line}" + "\n".join(lines)
        )
